/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package conversor_de_medidas;

import javax.swing.JOptionPane;

/**
 *
 * @author SYSTEM N.P
 */
public class Telaprograma extends javax.swing.JFrame {

    /**
     * Creates new form Telaprograma
     */
    public Telaprograma() {
        initComponents();
        
        setResizable(false);
        jTextField1.setEnabled(false);
        jTextField2.setEnabled(false);
        jTextField2.setEditable(false);
        jComboBox2.setEnabled(false);
        jComboBox3.setEnabled(false);
        jButton1.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jComboBox2 = new javax.swing.JComboBox<>();
        jComboBox3 = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(102, 102, 102));

        jPanel1.setBackground(new java.awt.Color(102, 102, 102));
        jPanel1.setForeground(new java.awt.Color(45, 45, 45));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Escolha o tipo de medida", "Medidas De Tempo", "Medidas De Distância" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        jPanel1.add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 20, -1, -1));

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Escolha o tipo de medida" }));
        jPanel1.add(jComboBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 130, -1, -1));

        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Escolha o tipo de medida" }));
        jComboBox3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox3ActionPerformed(evt);
            }
        });
        jPanel1.add(jComboBox3, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 130, -1, -1));

        jButton1.setText("Converter ➨");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 130, -1, -1));
        jPanel1.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 130, -1));
        jPanel1.add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 130, 140, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1031, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed

        switch ((String) jComboBox1.getSelectedItem()) {

            case "Medidas De Tempo":
                jComboBox2.removeAllItems();
                jComboBox2.addItem("Hora");
                jComboBox2.addItem("Minuto");
                jComboBox2.addItem("Segundo");
                jComboBox2.addItem("Semana");
                jComboBox2.addItem("Dia");
                jComboBox2.addItem("Mês");
                jComboBox2.addItem("Ano");
                jComboBox2.addItem("Década");
                jComboBox2.addItem("Século");

                jComboBox3.removeAllItems();
                jComboBox3.addItem("Hora");
                jComboBox3.addItem("Minuto");
                jComboBox3.addItem("Segundo");
                jComboBox3.addItem("Semana");
                jComboBox3.addItem("Dia");
                jComboBox2.addItem("Mês");
                jComboBox3.addItem("Ano");
                jComboBox3.addItem("Década");
                jComboBox3.addItem("Século");

                jTextField1.setEnabled(true);
                jTextField2.setEnabled(true);
                jComboBox2.setEnabled(true);
                jComboBox3.setEnabled(true);
                jButton1.setEnabled(true);

                break;

            case "Medidas De Distância":
                jComboBox2.removeAllItems();
                jComboBox2.addItem("Quilômetro (km)");
                jComboBox2.addItem("Hectômetro (hm)");
                jComboBox2.addItem("Decâmetro (dam)");
                jComboBox2.addItem("metro (m)");
                jComboBox2.addItem("Decímetro (dm)");
                jComboBox2.addItem("Centímetro (cm)");
                jComboBox2.addItem("Milímetro (mm)");

                jComboBox3.removeAllItems();
                jComboBox3.addItem("Quilômetro (km)");
                jComboBox3.addItem("Hectômetro (hm)");
                jComboBox3.addItem("Decâmetro (dam)");
                jComboBox3.addItem("metro (m)");
                jComboBox3.addItem("Decímetro (dm)");
                jComboBox3.addItem("Centímetro (cm)");
                jComboBox3.addItem("Milímetro (mm)");

                jTextField1.setEnabled(true);
                jTextField2.setEnabled(true);
                jComboBox2.setEnabled(true);
                jComboBox3.setEnabled(true);
                jButton1.setEnabled(true);
                break;

            case "Escolha o tipo de medida":
                jComboBox2.removeAllItems();
                jComboBox3.removeAllItems();
                jComboBox2.addItem("Escolha o tipo de medida");
                jComboBox3.addItem("Escolha o tipo de medida");

                jTextField1.setEnabled(false);
                jTextField2.setEnabled(false);
                jComboBox2.setEnabled(false);
                jComboBox3.setEnabled(false);
                jButton1.setEnabled(false);

                break;
        }


    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            if (!jTextField1.getText().isBlank()) {
                jTextField2.setText(Double.toString((Converter.converter(Double.valueOf(jTextField1.getText()), (String) jComboBox1.getSelectedItem(), (String) jComboBox2.getSelectedItem(), (String) jComboBox3.getSelectedItem()))));
            } else {
                JOptionPane.showMessageDialog(null, "informe a quantidade a ser convertida", "Erro", JOptionPane.ERROR_MESSAGE);
            }
        } catch (java.lang.NumberFormatException ex) {
            JOptionPane.showMessageDialog(null, "Tipo de valor informado inválido", "Erro", JOptionPane.ERROR_MESSAGE);

        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jComboBox3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Telaprograma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Telaprograma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Telaprograma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Telaprograma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Telaprograma().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration//GEN-END:variables
}
